matrix:
  include:
    - os: osx
      language: swift
      osx_image: xcode10.2
      install:
        - brew install mint
      before_script: 
        - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      script:
        - swift --version
        - pod repo update
        - fastlane ios test_carthage_unit
        - fastlane ios test_carthage_prototyping
        - fastlane ios test_pods_unit
        - fastlane ios test_pods_unit_static
        - fastlane ios test_pods_prototyping
        - fastlane spm test
    
notifications:
  email: false
