# use_frameworks!
platform :ios, "12.0"

target 'Unit' do
  # Pods for Unit

  target 'UnitTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SwiftyMocky', '~> 3.3.4'pod 'SwiftyMocky'
  end

end
