use_frameworks!
platform :ios, "12.0"

target 'Prototyping' do
  # Pods for Prototyping
  pod 'SwiftyMocky/Prototyping'

  target 'PrototypingTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SwiftyMocky', '~> 3.3.4'
  end

end
