use_frameworks!
platform :ios, "12.0"

target 'Prototyping' do
  # Pods for Prototyping
  pod 'SwiftyPrototype', :git => 'https://github.com/MakeAWishFoundation/SwiftyMocky.git', :branch => 'develop'

  target 'PrototypingTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SwiftyMocky', :git => 'https://github.com/MakeAWishFoundation/SwiftyMocky.git', :branch => 'develop'
  end

end

post_install do |installer|
  system("mint run swiftymocky generate")
end
