sources:
  include:
    - ./SwiftyMocky-Example/Shared
    - ./SwiftyMocky-Example/tvOS
    - ./SwiftyMocky-Tests/tvOS
  exclude:
    - ./SwiftyMocky-Example/Shared/Other/Excluded.generated.swift
templates:
  - ./Sources/Templates
output:
  ./SwiftyMocky-Tests/tvOS/Mocks
args:
  swiftyMocky: 
    testable:
      - Mocky_Example_tvOS
    excludedSwiftLintRules:
      - force_cast
      - function_body_length
      - line_length
      - vertical_whitespace
