env:
  global:
    - SWIFT_BRANCH=swift-5.0-release
    - SWIFT_VERSION=swift-5.0-RELEASE

matrix:
  include:
    - os: osx
      language: swift
      osx_image: xcode10
      install:
        - rake pods
        - brew install mint
      script:
        - swift --version
        - swift build -c release
        - sleep 1
        - ./.build/x86_64-apple-macosx10.10/release/swiftymocky doctor
        - ./.build/x86_64-apple-macosx10.10/release/swiftymocky generate
        - swift test
        - fastlane ios test
        - rake mock # legacy mock generation
        - fastlane tvos test

    - os: osx
      language: swift
      osx_image: xcode10.2
      install:
        - rake pods
        - brew install mint
      script:
        - swift --version
        - swift build -c release
        - swift run -c release --skip-build --skip-update swiftymocky doctor
        - swift run -c release --skip-build --skip-update swiftymocky generate
        - swift test
        - fastlane ios test
        - rake mock # legacy mock generation
        - fastlane tvos test
    
    # For now, Sourcery does not work on linux, so commented it out
    - os: linux
      dist: trusty
      sudo: required
      language: generic
      install:
        - sudo apt-get install clang libicu-dev
        - mkdir swift
        - curl https://swift.org/builds/$SWIFT_BRANCH/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz -s | tar xz -C swift &> /dev/null
        - export PATH="$(pwd)/swift/$SWIFT_VERSION-ubuntu14.04/usr/bin:$PATH"
        # - git clone https://github.com/yonaskolb/Mint.git
        # - cd Mint && swift run mint install yonaskolb/mint
      script:
        - swift --version
        - swift test

notifications:
  email: false
