matrix:
  include:
    - os: osx
      language: swift
      osx_image: xcode10.2
      install:
        - rake pods
      script:
        - rake mock # legacy mock generation
        - swift build
        - swift test
        - fastlane ios test
        - fastlane tvos test

    - os: osx
      language: swift
      osx_image: xcode11.2
      install:
        - rake pods
      script:
        - rake mock # legacy mock generation
        - swift build
        - swift test
        - fastlane ios test
        - fastlane tvos test_13

    - os: osx
      language: swift
      osx_image: xcode11.5
      install:
        - rake pods
      script:
        - rake mock # legacy mock generation
        - swift build
        - swift test
        - fastlane ios test
        - fastlane tvos test_13

notifications:
  email: false
