use_frameworks!
platform :ios, "12.0"

target 'Unit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Unit

  target 'UnitTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SwiftyMocky', :git => 'git@github.com:MakeAWishFoundation/SwiftyMocky.git', :branch => 'release/3.3.0'
  end

end
