use_frameworks!
platform :ios, "12.0"

target 'Unit' do
  # Pods for Unit

  target 'UnitTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SwiftyMocky', :git => 'https://github.com/MakeAWishFoundation/SwiftyMocky.git', :branch => 'release/3.3.0'
  end

end
