# name: CocoaPods Integration Tests
# on:
#   push:
#     branches:
#       - master

# jobs:
#   Run-Tests:
#     runs-on: macos-11
#     steps:
#       - name: Check out repository code
#         uses: actions/checkout@v2
#       - name: Set Xcode version
#         uses: maxim-lobanov/setup-xcode@v1
#         with:
#           xcode-version: '12.4.0'
#       - name: Run tests iOS
#         run: |
#           fastlane ios test_pods_unit
#           fastlane ios test_pods_unit_static
#           fastlane ios test_pods_prototyping
