name: SwiftPM Integration Tests
on:
  push:
    branches:
      - master

jobs:
  Run-Tests:
    runs-on: macos-11
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.4.0'
      - name: Run tests iOS
        run: |
          brew install mint
          mint install MakeAWishFoundation/SwiftyMocky@master
          mint install krzysztofzablocki/Sourcery@1.6.0
          PATH=$PATH:/Users/runner/.mint/bin
          fastlane spm test
          fastlane spm test_xcode_unit
          fastlane spm test_xcode_prototyping
